dist:     bionic
sudo:     required

language: c

os: linux

compiler: gcc

matrix:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-9
            - g++-9
      env:
        - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"

before_install:
    - eval "${MATRIX_EVAL}"

install:
    - sudo apt-get update
    - sudo apt-get install cmake
    - sudo apt-get install cppcheck

before_script:
    - ./linters/run.sh --local || travis_terminate 1
    - mkdir build
    - cd build
    - cmake -DCMAKE_C_COMPILER=/usr/bin/gcc-9 -DCMAKE_CXX_COMPILER=/usr/bin/g++-9 ..
    - make || travis_terminate 1
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:.
    - cd ..

script:
    - echo "exit" | ./build/simpledb
